### ISSUE TITLE
Help creating a user with "Admin" role

### ISSUE THREAD

**Issue by naftalimurgor** [amamenko/GlowLabs#63]
Hello @amamenko 
I need help:
- setting up/creating a user with the "Admin"

A user with admin roles as previlges:
* Add new staff members.
* Delete clients and staff members.
* Update all clients' and staff members' profile photos.
* View and manage all staff members' calendars.
as explained here:  https://github.com/amamenko/GlowLabs/blob/master/README.md
Looking forward to your feedback
much thanks,
Naftali Murgor

**Comment by amamenko** [comment]
To get started with the very first admin account, create a new employee in MongoDB with the attributes firstName, lastName, email, password, phoneNumber, employeeRole, and permanentPasswordSet attribute set to true. The employeeRole should be an array that contains, at minimum, the string “Admin” to allow additional admin privileges like creating additional staff members. You can add other roles but the "Admin" grants that specific employee the most privileges.

After you create that first admin account in MongoDB, you can log in on the admin page with the email and password you entered above, which will trigger a GraphQL admin login query that returns an admin dummy cookie, access cookie, and refresh cookie on the client side. You will then be redirected to the admin dashboard page.
